//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBelediyeOtomasyonu
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Adalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adalar()
        {
            this.MezarYerleri = new HashSet<MezarYerleri>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MezarlikId { get; set; }
        public Nullable<int> SaveUserId { get; set; }
        public string SaveDate { get; set; }
        public Nullable<int> EditUserId { get; set; }
        public string EditDate { get; set; }
        public string AdaNo { get; set; }
        public Nullable<int> MezarlikSayisi { get; set; }
        public string Detay { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Kullanicilar Kullanicilar1 { get; set; }
        public virtual Mezarliklar Mezarliklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezarYerleri> MezarYerleri { get; set; }
        public List<SelectListItem> MezarlikListesi { get; set; }
    }
}
