//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBelediyeOtomasyonu
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class KirsalYapiRuhsatlari
    {
        public int Id { get; set; }
        public Nullable<int> RuhsatTipId { get; set; }
        public Nullable<int> IskanTipId { get; set; }
        public Nullable<int> SaveUserId { get; set; }
        public string SaveDate { get; set; }
        public Nullable<int> EditUserId { get; set; }
        public string EditDate { get; set; }
        public string Tarih { get; set; }
        public string RuhsatNo { get; set; }
        public string YapiSahibi { get; set; }
        public string TcNo { get; set; }
        public string Mahalle { get; set; }
        public Nullable<int> Ada { get; set; }
        public Nullable<int> Parsel { get; set; }
        public Nullable<decimal> ParselAlani { get; set; }
        public Nullable<decimal> YapiAlani { get; set; }
        public string Adres { get; set; }
        public string YapiSinifi { get; set; }
        public string InsaatTuru { get; set; }
        public string KatSayisi { get; set; }
        public string MimariProjeMuellifi { get; set; }
        public string StatikProjeMuellifi { get; set; }
        public string ElektrikProjeMuellifi { get; set; }
        public string Tarama0 { get; set; }
        public string Tarama1 { get; set; }
        public string Tarama2 { get; set; }
        public string ProjeDosyasi { get; set; }
        public string Detay { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Kullanicilar Kullanicilar1 { get; set; }
        public virtual RuhsatTipleri RuhsatTipleri { get; set; }
        public List<SelectListItem> RuhsatTipListesi { get; set; }
    }
}
