//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBelediyeOtomasyonu
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Adalar = new HashSet<Adalar>();
            this.Adalar1 = new HashSet<Adalar>();
            this.KirsalYapiRuhsatlari = new HashSet<KirsalYapiRuhsatlari>();
            this.KirsalYapiRuhsatlari1 = new HashSet<KirsalYapiRuhsatlari>();
            this.KullaniciTipleri1 = new HashSet<KullaniciTipleri>();
            this.KullaniciTipleri2 = new HashSet<KullaniciTipleri>();
            this.Mezarliklar = new HashSet<Mezarliklar>();
            this.Mezarliklar1 = new HashSet<Mezarliklar>();
            this.MezarYerleri = new HashSet<MezarYerleri>();
            this.MezarYerleri1 = new HashSet<MezarYerleri>();
            this.Ruhsatlar = new HashSet<Ruhsatlar>();
            this.Ruhsatlar1 = new HashSet<Ruhsatlar>();
            this.RuhsatTipleri = new HashSet<RuhsatTipleri>();
            this.RuhsatTipleri1 = new HashSet<RuhsatTipleri>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SaveUserId { get; set; }
        public string SaveDate { get; set; }
        public Nullable<int> EditUserId { get; set; }
        public string EditDate { get; set; }
        public Nullable<int> KullaniciTipId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Unvan { get; set; }
        public string Birim { get; set; }
        public string TcKimlikNo { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> YetkiGiris { get; set; }
        public Nullable<bool> YetkiRuhsat { get; set; }
        public Nullable<bool> YetkiRuhsatYeni { get; set; }
        public Nullable<bool> YetkiRuhsatGoster { get; set; }
        public Nullable<bool> YetkiRuhsatDuzenle { get; set; }
        public Nullable<bool> YetkiRuhsatDetay { get; set; }
        public Nullable<bool> YetkiRuhsatSil { get; set; }
        public Nullable<bool> YetkiKirsalRuhsat { get; set; }
        public Nullable<bool> YetkiKirsalRuhsatYeni { get; set; }
        public Nullable<bool> YetkiKirsalRuhsatGoster { get; set; }
        public Nullable<bool> YetkiKirsalRuhsatDuzenle { get; set; }
        public Nullable<bool> YetkiKirsalRuhsatDetay { get; set; }
        public Nullable<bool> YetkiKirsalRuhsatSil { get; set; }
        public Nullable<bool> YetkiMezarlik { get; set; }
        public Nullable<bool> YetkiMezarlikYeni { get; set; }
        public Nullable<bool> YetkiMezarlikGoster { get; set; }
        public Nullable<bool> YetkiMezarlikDuzenle { get; set; }
        public Nullable<bool> YetkiMezarlikDetay { get; set; }
        public Nullable<bool> YetkiMezarlikSil { get; set; }
        public Nullable<bool> YetkiAdalar { get; set; }
        public Nullable<bool> YetkiAdalarYeni { get; set; }
        public Nullable<bool> YetkiAdalarGoster { get; set; }
        public Nullable<bool> YetkiAdalarDuzenle { get; set; }
        public Nullable<bool> YetkiAdalarDetay { get; set; }
        public Nullable<bool> YetkiAdalarSil { get; set; }
        public Nullable<bool> YetkiMezarYerleri { get; set; }
        public Nullable<bool> YetkiMezarYerleriYeni { get; set; }
        public Nullable<bool> YetkiMezarYerleriGoster { get; set; }
        public Nullable<bool> YetkiMezarYerleriDuzenle { get; set; }
        public Nullable<bool> YetkiMezarYerleriDetay { get; set; }
        public Nullable<bool> YetkiMezarYerleriSil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adalar> Adalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adalar> Adalar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KirsalYapiRuhsatlari> KirsalYapiRuhsatlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KirsalYapiRuhsatlari> KirsalYapiRuhsatlari1 { get; set; }
        public virtual KullaniciTipleri KullaniciTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciTipleri> KullaniciTipleri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciTipleri> KullaniciTipleri2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mezarliklar> Mezarliklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mezarliklar> Mezarliklar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezarYerleri> MezarYerleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezarYerleri> MezarYerleri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruhsatlar> Ruhsatlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruhsatlar> Ruhsatlar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuhsatTipleri> RuhsatTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuhsatTipleri> RuhsatTipleri1 { get; set; }
        public List<SelectListItem> KullaniciTipListesi { get; set; }
    }
}
