//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBelediyeOtomasyonu
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class MezarYerleri
    {
        public MezarYerleri()
        {
            this.AdaListesi = new List<SelectListItem>();
            AdaListesi.Insert(0, new SelectListItem { Text = "Öncelikle mezarlýk seçilmelidir...", Value = "" });
        }
        public int Id { get; set; }
        public Nullable<int> SaveUserId { get; set; }
        public string SaveDate { get; set; }
        public Nullable<int> EditUserId { get; set; }
        public string EditDate { get; set; }
        public Nullable<int> MezarlikId { get; set; }
        public Nullable<int> AdaId { get; set; }
        public Nullable<int> MezarNo { get; set; }
        public string TcNo { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Cinsiyet { get; set; }
        public string IrtibatNo { get; set; }
        public string DogumTarihi { get; set; }
        public string OlumTarihi { get; set; }
        public string DefinTarihi { get; set; }
        public string MakbuzNo { get; set; }
        public string MakbuzTarihi { get; set; }
        public string MakbuzTarama { get; set; }
        public string Durum { get; set; }
        public string Detay { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Adalar Adalar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Kullanicilar Kullanicilar1 { get; set; }
        public virtual Mezarliklar Mezarliklar { get; set; }
        public List<SelectListItem> AdaListesi { get; set; }

        public List<SelectListItem> MezarlikListesi { get; set; }
    }
}
